<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fort.MG.Engine\Fort.MG.Engine.csproj" />
    <ProjectReference Include="..\Fort.MG.Network.Messages\Fort.MG.Network.Messages.csproj" />
  </ItemGroup>

</Project>
